/* ===== TABLES ===== */
CREATE TABLE users (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    name        VARCHAR2(100) NOT NULL,
    email       VARCHAR(100) UNIQUE NOT NULL,
    password    VARCHAR2(20) NOT NULL,
    role        VARCHAR2(10) NOT NULL,
    balance     NUMBER(10,2),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT chk_user_role CHECK (role IN ('ADMIN', 'CLIENT')),
    CONSTRAINT chk_client_balance CHECK (
       (role = 'CLIENT' AND balance IS NOT NULL)
           OR
       (role = 'ADMIN' AND balance IS NULL)
       )
);

CREATE TABLE products (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 1),
    name        VARCHAR2(100) NOT NULL,
    price       NUMBER(10,2) NOT NULL,
    category    VARCHAR2(30) NOT NULL,
    stock       NUMBER NOT NULL,
    rating      NUMBER(2,1) NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT chk_product_price CHECK (price >= 0),
    CONSTRAINT chk_product_stock CHECK (stock >= 0),
    CONSTRAINT chk_product_rating CHECK (rating BETWEEN 0 AND 5)
);

CREATE TABLE receipts (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id     NUMBER NOT NULL,
    type        VARCHAR2(10) NOT NULL,
    date_op     DATE DEFAULT SYSDATE NOT NULL,
    total       NUMBER (10,2) NOT NULL,
    CONSTRAINT pk_receipt PRIMARY KEY (id),
    CONSTRAINT chk_receipt_type CHECK (type IN ('PURCHASE', 'RETURN')),
    CONSTRAINT chk_receipt_total CHECK (total >= 0),
    CONSTRAINT fk_receipt_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE receipt_item (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    receipt_id      NUMBER NOT NULL,
    product_id      NUMBER NOT NULL,
    unit_price      NUMBER(10,2) NOT NULL,
    quantity        NUMBER NOT NULL,
    subtotal        NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_receipt_item PRIMARY KEY (id),
    CONSTRAINT chk_item_quantity CHECK (quantity >= 0),
    CONSTRAINT chk_item_prices CHECK (unit_price >= 0 AND subtotal >= 0),
    CONSTRAINT fk_item_receipt FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE CASCADE,
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES products(id)
);
