CREATE USER kamazon_db IDENTIFIED BY kamazon_db_pw;

GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE,
    CREATE SEQUENCE,
    CREATE TYPE,
    CREATE TRIGGER
TO kamazon_db;

GRANT UNLIMITED TABLESPACE TO kamazon_db;