-- db/users-example.sql
CREATE USER admin IDENTIFIED BY <your_password>;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TYPE, CREATE TRIGGER TO admin;

CREATE USER client IDENTIFIED BY <your_password>;
GRANT CREATE SESSION TO client;
