CREATE USER <user> IDENTIFIED BY <your_password>;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TYPE, CREATE TRIGGER TO <user>
GRANT UNLIMITED TABLESPACE TO <user>;